version: "3.9"

networks:
  default:
    driver: bridge
    ipam:
      driver: default

volumes:
  db:
    driver: local

services:
  db:
    image: postgres:15.2-alpine3.17
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGUSER=${USER_NAME}

  importer:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      PORT: 5432
      USERNAME: ${USER_NAME}
      PASSWORD: ${PASSWORD}
      DB_NAME: ${DB_NAME}